openapi: 3.0.0
info:
  title: Boilerplate
  version: 1.0.0
  description: API boilerplate for common projects
servers:
  - url: https://boilerplateapi/api/v1
paths:
  /users/{userId}/data:
    get:
      summary: List all user's data
      parameters:
        - name: userId
          in: path
          schema:
            type: string
          required: true
          description: User ID of the user to get the data
        - name: search
          in: query
          schema:
            type: string
          description: Search Query to query the data from
          required: false
        - name: sort
          in: query
          schema:
            type: string
          description: Sort Query to sort the data in a specified order
          required: false
      responses:
        "200":
          description: A list of user's data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserdataArr"
        "404":
          description: User not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    UserdataArr:
      type: array
      items:
        type: object
        properties:
          id:
            type: number
          name:
            type: string
          data:
            type: string
